/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyChallenge {
  'id' : string,
  'targetScore' : bigint,
  'completed' : boolean,
  'rewardCoins' : bigint,
  'description' : string,
}
export interface HighScore { 'score' : bigint, 'gameName' : string }
export interface LeaderboardEntry {
  'xp' : bigint,
  'principal' : Principal,
  'rank' : string,
}
export interface UserProfile {
  'xp' : bigint,
  'gamesPlayed' : bigint,
  'weeklyXP' : bigint,
  'coins' : bigint,
  'rank' : string,
  'language' : string,
  'lastSpinDate' : bigint,
  'lastLogin' : bigint,
  'dailyStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimDailyLoginReward' : ActorMethod<
    [],
    { 'coinsAwarded' : bigint, 'currentStreak' : bigint }
  >,
  'completeChallenge' : ActorMethod<[string], { 'rewardCoins' : bigint }>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyChallenges' : ActorMethod<[], Array<DailyChallenge>>,
  'getHighScore' : ActorMethod<[string], [] | [HighScore]>,
  'getLanguagePreference' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setLanguagePreference' : ActorMethod<[string], undefined>,
  'spinAndWin' : ActorMethod<[], { 'rewardCoins' : bigint }>,
  'submitGameResult' : ActorMethod<[string, bigint, bigint, bigint], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];