/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'gamesPlayed' : IDL.Nat,
  'weeklyXP' : IDL.Nat,
  'coins' : IDL.Nat,
  'rank' : IDL.Text,
  'language' : IDL.Text,
  'lastSpinDate' : IDL.Int,
  'lastLogin' : IDL.Int,
  'dailyStreak' : IDL.Nat,
});
export const DailyChallenge = IDL.Record({
  'id' : IDL.Text,
  'targetScore' : IDL.Nat,
  'completed' : IDL.Bool,
  'rewardCoins' : IDL.Nat,
  'description' : IDL.Text,
});
export const HighScore = IDL.Record({
  'score' : IDL.Nat,
  'gameName' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'xp' : IDL.Nat,
  'principal' : IDL.Principal,
  'rank' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyLoginReward' : IDL.Func(
      [],
      [IDL.Record({ 'coinsAwarded' : IDL.Nat, 'currentStreak' : IDL.Nat })],
      [],
    ),
  'completeChallenge' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'rewardCoins' : IDL.Nat })],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyChallenges' : IDL.Func([], [IDL.Vec(DailyChallenge)], ['query']),
  'getHighScore' : IDL.Func([IDL.Text], [IDL.Opt(HighScore)], ['query']),
  'getLanguagePreference' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setLanguagePreference' : IDL.Func([IDL.Text], [], []),
  'spinAndWin' : IDL.Func([], [IDL.Record({ 'rewardCoins' : IDL.Nat })], []),
  'submitGameResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'gamesPlayed' : IDL.Nat,
    'weeklyXP' : IDL.Nat,
    'coins' : IDL.Nat,
    'rank' : IDL.Text,
    'language' : IDL.Text,
    'lastSpinDate' : IDL.Int,
    'lastLogin' : IDL.Int,
    'dailyStreak' : IDL.Nat,
  });
  const DailyChallenge = IDL.Record({
    'id' : IDL.Text,
    'targetScore' : IDL.Nat,
    'completed' : IDL.Bool,
    'rewardCoins' : IDL.Nat,
    'description' : IDL.Text,
  });
  const HighScore = IDL.Record({ 'score' : IDL.Nat, 'gameName' : IDL.Text });
  const LeaderboardEntry = IDL.Record({
    'xp' : IDL.Nat,
    'principal' : IDL.Principal,
    'rank' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyLoginReward' : IDL.Func(
        [],
        [IDL.Record({ 'coinsAwarded' : IDL.Nat, 'currentStreak' : IDL.Nat })],
        [],
      ),
    'completeChallenge' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'rewardCoins' : IDL.Nat })],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyChallenges' : IDL.Func([], [IDL.Vec(DailyChallenge)], ['query']),
    'getHighScore' : IDL.Func([IDL.Text], [IDL.Opt(HighScore)], ['query']),
    'getLanguagePreference' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setLanguagePreference' : IDL.Func([IDL.Text], [], []),
    'spinAndWin' : IDL.Func([], [IDL.Record({ 'rewardCoins' : IDL.Nat })], []),
    'submitGameResult' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };